name: Check README Update

on:
  pull_request:
    branches:
      - main

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check if README.md was updated
      run: |
        if git diff --name-only origin/main...HEAD | grep -q "^README.md$"; then
          echo "README.md has been updated."
        else
          echo "README.md has not been updated."
          exit 1
        fi
